// Code generated by goctl. DO NOT EDIT.
package types

type IdReq struct {
	Id int64 `json:"id"`
}

type UserInfoReply struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Number string `json:"number"`
	Gender string `json:"gender"`
}
