// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginReply struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}
