// Code generated by goctl. DO NOT EDIT.
package types

type UserReq struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type UserResp struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type UserResps struct {
	List []UserResp `json:"list"`
}
